export const GET_ERRORS = "GET_ERRORS";
export const GET_RECEIVED_MESSAGES = "GET_RECEIVED_MESSAGES";
export const GET_SENT_MESSAGES = "GET_SENT_MESSAGES";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
